### PR TITLE
switch to build on opensuse

### PR DESCRIPTION
**Pull request by yeesian**

### CODE REVIEW

**Comment by visr** [comment]
Awesome, thanks!
I'll try it out later today.

**Comment by yeesian** [comment]
Finally passing on AppVeyor for julia v0.4 😄

**Comment by yeesian** [comment]
I'd be okay if we close this PR, and move the opensuse changes into #23 instead

**Comment by visr** [comment]
No, let's just keep this related to OBS only and merge soon. Then from #23 we could pick 0f14e8a441b84f49eb73b15040aff0069a0d70cd and 483099e5613579d51ca2ae657d3c95e0a9876043 and leave the rest.

Just managed to test this locally as well (after removing many a GDAL from my path and reinstalling WinRPM).

I got a warning, though it seems harmless:
```
INFO: Downloading http://download.opensuse.org/repositories/home:yeesian/openSUSE_13.2/repodata/repomd.xml
WARNING: Package not found that provides mingw64(odbccp32.dll)
INFO: Packages to update:  libgeos-devel, libgeos, libgcc_s_seh1, libstdc++6
INFO: Packages to install: libgdal
```

Also closes #24 :)
Feel free to merge when you're done.

**Comment by yeesian** [comment]
I don't know how to interpret that message too, haha. @tkelman?

**Comment by tkelman** [comment]
Is that a library name that sounds familiar or relevant?

**Comment by visr** [comment]
I guess it must be related to [GDAL's ODBC driver](http://www.gdal.org/drv_odbc.html). ODBC is in the list of 158 GDAL drivers that the OBS GDAL has.

**Comment by visr** [comment]
I don't have any ODBC geo data at hand that I can test if the driver works, but using Dependency Walker on `libgdal-20.dll`, I see that it finds this one instead without complaining:
`c:\Windows\System32\odbccp32.dll`

**Comment by yeesian** [comment]
I'm going to modify [the spec file](https://build.opensuse.org/package/show/home:yeesian/mingw64-gdal)'s basename to `gdal` in response to the following lint warning

```
[ 1106s] mingw64-libgdal.src: W: invalid-spec-name
[ 1106s] The spec file name (without the .spec suffix) must match the package name
[ 1106s] ("Name:" tag). Either rename your package or the specfile.
```

and revert https://github.com/visr/GDAL.jl/pull/25/commits/617fc338c6f3dd84b0ca7206d373d7807dbe36d5

**Comment by visr** [comment]
Astonishingly relevant: http://www.bostongis.com/blog/index.php?/archives/237-Building-GDAL-under-mingw-w64-with-native-windows-ODBC-support.html

**Comment by yeesian** [comment]
updated with the instructions from regina

image

**Comment by visr** [comment]
Hmm I still get the same warning. Don't have much time to dive into it right now, so I'm also fine with merging this, and looking at it in more detail later. AppVeyor show the same warning by the way:
https://ci.appveyor.com/project/visr/gdal-jl/build/1.0.19/job/j3go2i76ewm4wu64#L73

**Comment by tkelman** [comment]
I think the warning might be harmless. That library comes from the OS, so on the cross-compile build system it's not available.

**Pull request merged**
